[2025-02-22T23:43:21.671-0500] {processor.py:186} INFO - Started process (PID=26563) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:43:21.673-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-22T23:43:21.678-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:21.677-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:43:21.696-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:21.693-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:43:21.697-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:43:21.739-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.082 seconds
[2025-02-22T23:44:31.229-0500] {processor.py:186} INFO - Started process (PID=27048) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:44:31.231-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-22T23:44:31.236-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:31.236-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:44:31.247-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:31.246-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:44:31.247-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:44:31.285-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.065 seconds
[2025-02-22T23:49:06.010-0500] {processor.py:186} INFO - Started process (PID=27694) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:49:06.012-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-22T23:49:06.015-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:06.014-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:49:06.028-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:06.027-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:49:06.028-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:49:06.059-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.058 seconds
[2025-02-22T23:50:09.063-0500] {processor.py:186} INFO - Started process (PID=28143) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:50:09.065-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-22T23:50:09.068-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:09.067-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:50:09.081-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:09.080-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:50:09.082-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:50:09.112-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.059 seconds
[2025-02-22T23:51:06.413-0500] {processor.py:186} INFO - Started process (PID=28508) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:51:06.415-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-22T23:51:06.418-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:06.417-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:51:06.429-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:06.427-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:51:06.429-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:51:06.455-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.051 seconds
[2025-02-22T23:52:03.933-0500] {processor.py:186} INFO - Started process (PID=28954) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:52:03.935-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-22T23:52:03.937-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:03.937-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:52:03.947-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:03.946-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:52:03.948-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:52:03.979-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.054 seconds
[2025-02-22T23:53:06.688-0500] {processor.py:186} INFO - Started process (PID=29382) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:53:06.690-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-22T23:53:06.692-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:53:06.692-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:53:06.706-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:53:06.705-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:53:06.706-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:53:06.737-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.059 seconds
[2025-02-22T23:53:39.488-0500] {processor.py:186} INFO - Started process (PID=29628) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:53:39.490-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-22T23:53:39.497-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:53:39.496-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:53:39.507-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:53:39.506-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:53:39.507-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:53:39.539-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.060 seconds
[2025-02-22T23:54:46.226-0500] {processor.py:186} INFO - Started process (PID=30095) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:54:46.228-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-22T23:54:46.236-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:46.231-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:54:46.260-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:46.257-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:54:46.260-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:54:46.290-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.076 seconds
[2025-02-22T23:57:56.422-0500] {processor.py:186} INFO - Started process (PID=30590) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:57:56.426-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-22T23:57:56.431-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:57:56.429-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:57:56.456-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:57:56.451-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:57:56.457-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:57:56.493-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.086 seconds
[2025-02-22T23:58:42.702-0500] {processor.py:186} INFO - Started process (PID=30913) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:58:42.706-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-22T23:58:42.709-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:42.708-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:58:42.721-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:42.720-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:58:42.722-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:58:42.752-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.061 seconds
[2025-02-22T23:59:54.777-0500] {processor.py:186} INFO - Started process (PID=31357) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:59:54.795-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-22T23:59:54.805-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:54.798-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:59:54.865-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:54.852-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:59:54.866-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-22T23:59:54.998-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.255 seconds
[2025-02-23T00:01:11.514-0500] {processor.py:186} INFO - Started process (PID=31903) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:01:11.516-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T00:01:11.519-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:11.519-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:01:11.538-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:11.535-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:01:11.539-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:01:11.600-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.096 seconds
[2025-02-23T00:11:06.261-0500] {processor.py:186} INFO - Started process (PID=34407) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:11:06.263-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T00:11:06.272-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:06.271-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:11:06.283-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:06.282-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:11:06.283-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:11:06.319-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.070 seconds
[2025-02-23T00:12:06.913-0500] {processor.py:186} INFO - Started process (PID=34499) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:12:06.915-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T00:12:06.918-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:06.918-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:12:06.929-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:06.928-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:12:06.930-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:12:06.962-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.057 seconds
[2025-02-23T00:13:22.215-0500] {processor.py:186} INFO - Started process (PID=34608) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:13:22.222-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T00:13:22.225-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:22.224-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:13:22.235-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:22.234-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:13:22.235-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:13:22.265-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.060 seconds
[2025-02-23T00:14:18.598-0500] {processor.py:186} INFO - Started process (PID=34683) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:14:18.605-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T00:14:18.608-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:18.607-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:14:18.619-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:18.617-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:14:18.619-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:14:18.652-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.063 seconds
[2025-02-23T00:15:28.869-0500] {processor.py:186} INFO - Started process (PID=34777) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:15:28.876-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T00:15:28.883-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:28.883-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:15:28.894-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:28.893-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:15:28.894-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:15:28.927-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.067 seconds
[2025-02-23T00:16:29.086-0500] {processor.py:186} INFO - Started process (PID=34879) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:16:29.088-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T00:16:29.102-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:29.093-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:16:29.138-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:29.136-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:16:29.139-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:16:29.303-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.260 seconds
[2025-02-23T00:17:32.900-0500] {processor.py:186} INFO - Started process (PID=34954) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:17:32.908-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T00:17:32.911-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:32.910-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:17:32.920-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:32.919-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:17:32.920-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:17:32.952-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.061 seconds
[2025-02-23T00:18:33.337-0500] {processor.py:186} INFO - Started process (PID=35024) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:18:33.339-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T00:18:33.342-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:33.341-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:18:33.351-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:33.350-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:18:33.352-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:18:33.388-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.060 seconds
[2025-02-23T00:21:48.603-0500] {processor.py:186} INFO - Started process (PID=35163) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:21:48.606-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T00:21:48.613-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:21:48.613-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:21:48.627-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:21:48.625-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:21:48.627-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:21:48.660-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.066 seconds
[2025-02-23T00:22:49.229-0500] {processor.py:186} INFO - Started process (PID=35231) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:22:49.236-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T00:22:49.239-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:49.238-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:22:49.249-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:49.248-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:22:49.249-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:22:49.279-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.063 seconds
[2025-02-23T00:23:50.675-0500] {processor.py:186} INFO - Started process (PID=35296) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:23:50.677-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T00:23:50.681-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:50.680-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:23:50.698-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:50.697-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:23:50.698-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:23:50.780-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.125 seconds
[2025-02-23T00:24:53.764-0500] {processor.py:186} INFO - Started process (PID=35374) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:24:53.766-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T00:24:53.768-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:53.768-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:24:53.781-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:53.779-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:24:53.781-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:24:53.814-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.060 seconds
[2025-02-23T00:25:53.253-0500] {processor.py:186} INFO - Started process (PID=35441) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:25:53.260-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T00:25:53.265-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:53.264-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:25:53.283-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:53.279-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:25:53.284-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T00:25:53.316-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.076 seconds
[2025-02-23T02:31:33.966-0500] {processor.py:186} INFO - Started process (PID=75961) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:31:33.973-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:31:33.976-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:33.975-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:31:33.985-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:33.984-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:31:33.986-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:31:34.023-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.066 seconds
[2025-02-23T02:32:34.041-0500] {processor.py:186} INFO - Started process (PID=76387) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:32:34.048-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:32:34.052-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:34.051-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:32:34.061-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:34.060-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:32:34.062-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:32:34.092-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.059 seconds
[2025-02-23T02:33:51.240-0500] {processor.py:186} INFO - Started process (PID=76783) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:33:51.242-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:33:51.245-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:33:51.244-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:33:51.254-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:33:51.254-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:33:51.255-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:33:51.287-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.056 seconds
[2025-02-23T02:35:15.326-0500] {processor.py:186} INFO - Started process (PID=77109) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:35:15.970-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:35:16.017-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:35:16.017-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:35:16.158-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:35:16.145-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:35:16.161-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:35:16.595-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 1.373 seconds
[2025-02-23T02:43:03.280-0500] {processor.py:186} INFO - Started process (PID=79020) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:43:03.282-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:43:03.285-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:03.285-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:43:03.295-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:03.293-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:43:03.295-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:43:03.324-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.056 seconds
[2025-02-23T02:44:01.792-0500] {processor.py:186} INFO - Started process (PID=79217) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:44:01.794-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:44:01.797-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:01.796-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:44:01.806-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:01.805-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:44:01.806-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:44:01.838-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.054 seconds
[2025-02-23T02:45:06.355-0500] {processor.py:186} INFO - Started process (PID=79417) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:45:06.362-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:45:06.367-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:45:06.367-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:45:06.381-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:45:06.380-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:45:06.382-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:45:06.420-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.084 seconds
[2025-02-23T02:46:06.901-0500] {processor.py:186} INFO - Started process (PID=79610) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:46:06.903-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:46:06.907-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:46:06.906-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:46:06.916-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:46:06.915-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:46:06.916-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:46:06.948-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.055 seconds
[2025-02-23T02:47:17.925-0500] {processor.py:186} INFO - Started process (PID=79854) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:47:17.931-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:47:17.936-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:47:17.935-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:47:17.955-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:47:17.954-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:47:17.956-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:47:18.001-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.088 seconds
[2025-02-23T02:48:19.206-0500] {processor.py:186} INFO - Started process (PID=80045) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:48:19.212-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:48:19.215-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:48:19.214-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:48:19.225-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:48:19.224-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:48:19.225-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:48:19.254-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.057 seconds
[2025-02-23T02:49:22.014-0500] {processor.py:186} INFO - Started process (PID=80243) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:49:22.017-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:49:22.022-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:49:22.021-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:49:22.037-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:49:22.033-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:49:22.038-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:49:22.085-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.083 seconds
[2025-02-23T02:50:20.615-0500] {processor.py:186} INFO - Started process (PID=80399) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:50:20.618-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:50:20.630-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:50:20.629-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:50:20.675-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:50:20.663-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:50:20.676-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:50:20.836-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.256 seconds
[2025-02-23T02:51:37.844-0500] {processor.py:186} INFO - Started process (PID=80650) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:51:37.846-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:51:37.849-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:51:37.849-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:51:37.860-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:51:37.859-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:51:37.860-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:51:37.889-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.053 seconds
[2025-02-23T02:52:46.817-0500] {processor.py:186} INFO - Started process (PID=80857) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:52:46.824-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:52:46.827-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:52:46.827-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:52:46.837-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:52:46.836-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:52:46.838-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:52:46.874-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.065 seconds
[2025-02-23T02:53:48.405-0500] {processor.py:186} INFO - Started process (PID=81043) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:53:48.406-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:53:48.411-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:53:48.410-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:53:48.423-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:53:48.421-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:53:48.424-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:53:48.484-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.089 seconds
[2025-02-23T02:54:54.232-0500] {processor.py:186} INFO - Started process (PID=81247) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:54:54.234-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:54:54.237-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:54:54.237-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:54:54.247-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:54:54.246-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:54:54.247-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:54:54.279-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.056 seconds
[2025-02-23T02:55:56.608-0500] {processor.py:186} INFO - Started process (PID=81440) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:55:56.610-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:55:56.614-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:55:56.614-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:55:56.624-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:55:56.623-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:55:56.625-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:55:56.658-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.059 seconds
[2025-02-23T02:56:55.994-0500] {processor.py:186} INFO - Started process (PID=81646) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:56:56.146-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:56:56.150-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:56:56.149-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:56:56.167-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:56:56.165-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:56:56.167-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:56:56.210-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.227 seconds
[2025-02-23T02:58:03.764-0500] {processor.py:186} INFO - Started process (PID=81883) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:58:03.770-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:58:03.774-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:58:03.774-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:58:03.791-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:58:03.790-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:58:03.791-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:58:03.837-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.082 seconds
[2025-02-23T02:59:04.154-0500] {processor.py:186} INFO - Started process (PID=82068) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:59:04.156-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T02:59:04.159-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:59:04.158-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:59:04.169-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:59:04.168-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:59:04.169-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T02:59:04.212-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.070 seconds
[2025-02-23T03:00:06.647-0500] {processor.py:186} INFO - Started process (PID=82261) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:00:06.654-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:00:06.657-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:00:06.657-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:00:06.667-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:00:06.666-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:00:06.668-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:00:06.697-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.061 seconds
[2025-02-23T03:01:14.275-0500] {processor.py:186} INFO - Started process (PID=82479) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:01:14.278-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:01:14.281-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:01:14.280-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:01:14.291-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:01:14.290-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:01:14.292-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:01:14.328-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.062 seconds
[2025-02-23T03:02:25.845-0500] {processor.py:186} INFO - Started process (PID=82729) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:02:25.847-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:02:25.850-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:02:25.850-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:02:25.861-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:02:25.860-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:02:25.861-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:02:25.891-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.056 seconds
[2025-02-23T03:03:44.707-0500] {processor.py:186} INFO - Started process (PID=83580) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:03:44.709-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:03:44.713-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:03:44.712-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:03:44.723-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:03:44.722-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:03:44.723-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:03:44.780-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.084 seconds
[2025-02-23T03:04:52.338-0500] {processor.py:186} INFO - Started process (PID=83783) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:04:52.340-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:04:52.343-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:04:52.343-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:04:52.353-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:04:52.352-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:04:52.354-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:04:52.387-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.057 seconds
[2025-02-23T03:05:55.388-0500] {processor.py:186} INFO - Started process (PID=83976) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:05:55.395-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:05:55.398-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:05:55.398-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:05:55.408-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:05:55.407-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:05:55.409-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:05:55.444-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.064 seconds
[2025-02-23T03:06:54.537-0500] {processor.py:186} INFO - Started process (PID=84186) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:06:54.539-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:06:54.542-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:06:54.541-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:06:54.557-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:06:54.554-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:06:54.558-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:06:54.593-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.070 seconds
[2025-02-23T03:07:53.534-0500] {processor.py:186} INFO - Started process (PID=84371) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:07:53.538-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:07:53.542-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:07:53.541-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:07:53.557-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:07:53.555-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:07:53.557-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:07:53.591-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.069 seconds
[2025-02-23T03:08:59.283-0500] {processor.py:186} INFO - Started process (PID=84575) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:08:59.285-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:08:59.288-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:08:59.287-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:08:59.298-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:08:59.297-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:08:59.299-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:08:59.328-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.054 seconds
[2025-02-23T03:10:09.241-0500] {processor.py:186} INFO - Started process (PID=84813) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:10:09.244-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:10:09.247-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:10:09.246-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:10:09.257-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:10:09.256-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:10:09.257-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:10:09.290-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.058 seconds
[2025-02-23T03:11:08.795-0500] {processor.py:186} INFO - Started process (PID=85002) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:11:08.797-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:11:08.800-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:11:08.800-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:11:08.812-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:11:08.811-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:11:08.812-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:11:08.848-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.062 seconds
[2025-02-23T03:12:14.455-0500] {processor.py:186} INFO - Started process (PID=85232) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:12:14.457-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:12:14.460-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:12:14.460-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:12:14.472-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:12:14.471-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:12:14.473-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:12:14.508-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.062 seconds
[2025-02-23T03:13:14.761-0500] {processor.py:186} INFO - Started process (PID=85418) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:13:14.763-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:13:14.766-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:13:14.766-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:13:14.777-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:13:14.776-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:13:14.777-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:13:14.808-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.056 seconds
[2025-02-23T03:14:24.674-0500] {processor.py:186} INFO - Started process (PID=85672) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:14:24.677-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:14:24.683-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:14:24.682-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:14:24.696-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:14:24.694-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:14:24.696-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:14:24.727-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.062 seconds
[2025-02-23T03:15:33.208-0500] {processor.py:186} INFO - Started process (PID=85893) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:15:33.210-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:15:33.213-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:15:33.213-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:15:33.223-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:15:33.222-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:15:33.224-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:15:33.268-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.068 seconds
[2025-02-23T03:16:31.903-0500] {processor.py:186} INFO - Started process (PID=86115) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:16:31.910-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:16:31.912-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:16:31.912-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:16:31.922-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:16:31.921-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:16:31.922-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:16:31.954-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.059 seconds
[2025-02-23T03:17:33.503-0500] {processor.py:186} INFO - Started process (PID=86309) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:17:33.510-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:17:33.515-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:17:33.515-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:17:33.534-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:17:33.532-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:17:33.535-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:17:33.575-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.088 seconds
[2025-02-23T03:18:36.150-0500] {processor.py:186} INFO - Started process (PID=86596) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:18:36.156-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:18:36.159-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:18:36.158-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:18:36.169-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:18:36.168-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:18:36.169-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:18:36.202-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.061 seconds
[2025-02-23T03:19:39.267-0500] {processor.py:186} INFO - Started process (PID=86825) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:19:39.274-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:19:39.279-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:19:39.278-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:19:39.294-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:19:39.292-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:19:39.295-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:19:39.339-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.081 seconds
[2025-02-23T03:20:41.844-0500] {processor.py:186} INFO - Started process (PID=87025) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:20:41.846-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py for tasks to queue
[2025-02-23T03:20:41.850-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:20:41.849-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:20:41.868-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:20:41.867-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py", line 44, in <module>
    def read_dataset_event(*, inlet_events=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:20:41.868-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py
[2025-02-23T03:20:41.903-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_inlet_event_extra.py took 0.067 seconds
