[2025-02-22T23:43:29.565-0500] {processor.py:186} INFO - Started process (PID=26599) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:43:29.567-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-22T23:43:29.570-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:29.570-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:43:29.593-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:29.589-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:43:29.593-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:43:29.638-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.091 seconds
[2025-02-22T23:44:40.922-0500] {processor.py:186} INFO - Started process (PID=27090) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:44:40.942-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-22T23:44:40.947-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:40.946-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:44:40.980-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:40.967-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:44:40.981-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:44:41.065-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.168 seconds
[2025-02-22T23:49:13.848-0500] {processor.py:186} INFO - Started process (PID=27726) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:49:13.851-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-22T23:49:13.857-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:13.855-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:49:13.874-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:13.871-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:49:13.875-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:49:13.912-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.080 seconds
[2025-02-22T23:50:16.666-0500] {processor.py:186} INFO - Started process (PID=28169) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:50:16.668-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-22T23:50:16.672-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:16.671-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:50:16.684-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:16.682-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:50:16.684-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:50:16.714-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.056 seconds
[2025-02-22T23:51:13.567-0500] {processor.py:186} INFO - Started process (PID=28590) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:51:13.569-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-22T23:51:13.573-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:13.573-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:51:13.602-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:13.595-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:51:13.603-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:51:13.639-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.088 seconds
[2025-02-22T23:52:11.645-0500] {processor.py:186} INFO - Started process (PID=29002) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:52:11.647-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-22T23:52:11.651-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:11.650-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:52:11.671-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:11.668-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:52:11.672-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:52:11.707-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.074 seconds
[2025-02-22T23:53:47.186-0500] {processor.py:186} INFO - Started process (PID=29653) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:53:47.193-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-22T23:53:47.196-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:53:47.195-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:53:47.205-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:53:47.203-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:53:47.205-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:53:47.239-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.064 seconds
[2025-02-22T23:54:53.049-0500] {processor.py:186} INFO - Started process (PID=30120) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:54:53.051-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-22T23:54:53.053-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:53.053-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:54:53.062-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:53.060-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:54:53.062-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:54:53.093-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.053 seconds
[2025-02-22T23:58:05.514-0500] {processor.py:186} INFO - Started process (PID=30657) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:58:05.516-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-22T23:58:05.520-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:05.519-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:58:05.536-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:05.533-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:58:05.536-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:58:05.574-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.074 seconds
[2025-02-22T23:59:10.218-0500] {processor.py:186} INFO - Started process (PID=31106) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:59:10.222-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-22T23:59:10.225-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:10.225-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:59:10.235-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:10.233-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:59:10.236-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-22T23:59:10.281-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.074 seconds
[2025-02-23T00:00:33.444-0500] {processor.py:186} INFO - Started process (PID=31645) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:00:33.447-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T00:00:33.450-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:33.449-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:00:33.458-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:33.456-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:00:33.459-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:00:33.492-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.061 seconds
[2025-02-23T00:01:36.363-0500] {processor.py:186} INFO - Started process (PID=32093) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:01:36.365-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T00:01:36.370-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:36.369-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:01:36.379-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:36.377-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:01:36.379-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:01:36.409-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.055 seconds
[2025-02-23T00:11:13.968-0500] {processor.py:186} INFO - Started process (PID=34418) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:11:13.970-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T00:11:13.973-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:13.972-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:11:13.981-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:13.979-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:11:13.982-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:11:14.007-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.048 seconds
[2025-02-23T00:12:15.395-0500] {processor.py:186} INFO - Started process (PID=34508) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:12:15.399-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T00:12:15.402-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:15.401-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:12:15.410-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:15.408-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:12:15.410-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:12:15.454-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.069 seconds
[2025-02-23T00:13:28.748-0500] {processor.py:186} INFO - Started process (PID=34615) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:13:28.755-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T00:13:28.757-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:28.757-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:13:28.766-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:28.764-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:13:28.767-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:13:28.801-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.062 seconds
[2025-02-23T00:14:25.620-0500] {processor.py:186} INFO - Started process (PID=34691) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:14:25.622-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T00:14:25.627-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:25.627-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:14:25.636-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:25.634-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:14:25.636-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:14:25.666-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.059 seconds
[2025-02-23T00:15:35.792-0500] {processor.py:186} INFO - Started process (PID=34786) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:15:35.794-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T00:15:35.798-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:35.797-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:15:35.806-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:35.804-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:15:35.806-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:15:35.837-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.054 seconds
[2025-02-23T00:16:36.717-0500] {processor.py:186} INFO - Started process (PID=34886) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:16:36.723-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T00:16:36.726-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:36.726-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:16:36.734-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:36.732-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:16:36.735-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:16:36.764-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.056 seconds
[2025-02-23T00:17:40.099-0500] {processor.py:186} INFO - Started process (PID=34967) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:17:40.100-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T00:17:40.105-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:40.105-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:17:40.116-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:40.114-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:17:40.116-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:17:40.160-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.072 seconds
[2025-02-23T00:18:40.367-0500] {processor.py:186} INFO - Started process (PID=35033) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:18:40.373-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T00:18:40.376-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:40.376-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:18:40.384-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:40.382-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:18:40.384-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:18:40.415-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.056 seconds
[2025-02-23T00:21:55.766-0500] {processor.py:186} INFO - Started process (PID=35173) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:21:55.768-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T00:21:55.771-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:21:55.770-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:21:55.780-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:21:55.778-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:21:55.780-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:21:55.807-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.050 seconds
[2025-02-23T00:22:56.463-0500] {processor.py:186} INFO - Started process (PID=35238) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:22:56.465-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T00:22:56.467-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:56.467-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:22:56.475-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:56.473-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:22:56.475-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:22:56.505-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.051 seconds
[2025-02-23T00:23:59.026-0500] {processor.py:186} INFO - Started process (PID=35305) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:23:59.027-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T00:23:59.031-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:59.031-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:23:59.040-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:59.038-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:23:59.040-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:23:59.071-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.055 seconds
[2025-02-23T00:25:01.286-0500] {processor.py:186} INFO - Started process (PID=35381) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:25:01.287-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T00:25:01.290-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:01.290-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:25:01.298-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:01.296-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:25:01.298-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:25:01.333-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.056 seconds
[2025-02-23T00:26:00.273-0500] {processor.py:186} INFO - Started process (PID=35448) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:26:00.275-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T00:26:00.277-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:26:00.277-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:26:00.285-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:26:00.283-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:26:00.285-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T00:26:00.318-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.054 seconds
[2025-02-23T02:31:36.923-0500] {processor.py:186} INFO - Started process (PID=75970) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:31:36.929-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:31:36.933-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:36.933-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:31:36.941-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:36.939-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:31:36.942-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:31:36.980-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.068 seconds
[2025-02-23T02:32:37.440-0500] {processor.py:186} INFO - Started process (PID=76400) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:32:37.442-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:32:37.445-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:37.444-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:32:37.454-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:37.452-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:32:37.455-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:32:37.490-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.063 seconds
[2025-02-23T02:33:54.715-0500] {processor.py:186} INFO - Started process (PID=76792) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:33:54.718-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:33:54.730-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:33:54.729-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:33:54.749-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:33:54.746-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:33:54.749-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:33:54.821-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.131 seconds
[2025-02-23T02:35:20.648-0500] {processor.py:186} INFO - Started process (PID=77125) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:35:20.650-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:35:20.653-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:35:20.652-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:35:20.660-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:35:20.659-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:35:20.661-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:35:20.699-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.059 seconds
[2025-02-23T02:43:06.005-0500] {processor.py:186} INFO - Started process (PID=79029) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:43:06.006-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:43:06.010-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:06.009-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:43:06.018-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:06.016-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:43:06.019-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:43:06.058-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.065 seconds
[2025-02-23T02:44:05.009-0500] {processor.py:186} INFO - Started process (PID=79226) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:44:05.011-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:44:05.013-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:05.013-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:44:05.021-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:05.019-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:44:05.021-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:44:05.052-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.051 seconds
[2025-02-23T02:45:09.756-0500] {processor.py:186} INFO - Started process (PID=79426) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:45:09.758-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:45:09.761-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:45:09.760-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:45:09.770-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:45:09.768-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:45:09.771-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:45:09.798-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.053 seconds
[2025-02-23T02:46:08.977-0500] {processor.py:186} INFO - Started process (PID=79619) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:46:08.979-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:46:08.983-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:46:08.982-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:46:08.991-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:46:08.989-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:46:08.992-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:46:09.025-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.056 seconds
[2025-02-23T02:47:20.040-0500] {processor.py:186} INFO - Started process (PID=79863) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:47:20.042-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:47:20.045-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:47:20.044-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:47:20.054-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:47:20.052-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:47:20.054-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:47:20.085-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.054 seconds
[2025-02-23T02:48:22.453-0500] {processor.py:186} INFO - Started process (PID=80054) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:48:22.460-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:48:22.463-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:48:22.463-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:48:22.471-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:48:22.469-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:48:22.471-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:48:22.503-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.058 seconds
[2025-02-23T02:49:25.641-0500] {processor.py:186} INFO - Started process (PID=80252) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:49:25.648-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:49:25.651-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:49:25.651-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:49:25.659-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:49:25.657-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:49:25.660-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:49:25.690-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.057 seconds
[2025-02-23T02:50:24.437-0500] {processor.py:186} INFO - Started process (PID=80408) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:50:24.439-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:50:24.444-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:50:24.443-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:50:24.456-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:50:24.455-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:50:24.457-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:50:24.498-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.074 seconds
[2025-02-23T02:51:41.486-0500] {processor.py:186} INFO - Started process (PID=80665) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:51:41.488-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:51:41.491-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:51:41.490-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:51:41.500-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:51:41.497-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:51:41.500-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:51:41.533-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.056 seconds
[2025-02-23T02:52:49.838-0500] {processor.py:186} INFO - Started process (PID=80866) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:52:49.840-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:52:49.843-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:52:49.843-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:52:49.852-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:52:49.850-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:52:49.853-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:52:49.890-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.060 seconds
[2025-02-23T02:53:51.156-0500] {processor.py:186} INFO - Started process (PID=81054) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:53:51.163-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:53:51.166-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:53:51.165-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:53:51.174-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:53:51.172-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:53:51.175-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:53:51.208-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.061 seconds
[2025-02-23T02:54:57.046-0500] {processor.py:186} INFO - Started process (PID=81258) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:54:57.048-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:54:57.054-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:54:57.053-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:54:57.065-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:54:57.063-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:54:57.066-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:54:57.106-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.073 seconds
[2025-02-23T02:55:59.435-0500] {processor.py:186} INFO - Started process (PID=81449) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:55:59.437-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:55:59.440-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:55:59.439-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:55:59.448-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:55:59.446-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:55:59.449-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:55:59.482-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.059 seconds
[2025-02-23T02:56:59.484-0500] {processor.py:186} INFO - Started process (PID=81655) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:56:59.491-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:56:59.495-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:56:59.494-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:56:59.505-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:56:59.502-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:56:59.506-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:56:59.542-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.068 seconds
[2025-02-23T02:58:06.773-0500] {processor.py:186} INFO - Started process (PID=81892) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:58:06.775-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:58:06.779-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:58:06.778-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:58:06.788-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:58:06.787-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:58:06.789-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:58:06.835-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.071 seconds
[2025-02-23T02:59:07.364-0500] {processor.py:186} INFO - Started process (PID=82083) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:59:07.366-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T02:59:07.369-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:59:07.368-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:59:07.378-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:59:07.376-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:59:07.379-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T02:59:07.414-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.058 seconds
[2025-02-23T03:00:09.935-0500] {processor.py:186} INFO - Started process (PID=82270) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:00:09.938-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:00:09.951-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:00:09.950-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:00:09.962-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:00:09.960-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:00:09.963-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:00:09.989-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.072 seconds
[2025-02-23T03:01:17.305-0500] {processor.py:186} INFO - Started process (PID=82502) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:01:17.307-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:01:17.310-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:01:17.309-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:01:17.318-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:01:17.316-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:01:17.319-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:01:17.352-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.056 seconds
[2025-02-23T03:02:29.186-0500] {processor.py:186} INFO - Started process (PID=82738) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:02:29.190-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:02:29.194-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:02:29.194-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:02:29.212-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:02:29.208-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:02:29.212-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:02:29.265-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.115 seconds
[2025-02-23T03:03:47.968-0500] {processor.py:186} INFO - Started process (PID=83589) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:03:47.975-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:03:47.978-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:03:47.977-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:03:47.988-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:03:47.986-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:03:47.988-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:03:48.020-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.061 seconds
[2025-02-23T03:04:54.831-0500] {processor.py:186} INFO - Started process (PID=83792) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:04:54.837-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:04:54.840-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:04:54.840-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:04:54.853-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:04:54.851-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:04:54.853-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:04:54.894-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.078 seconds
[2025-02-23T03:05:58.320-0500] {processor.py:186} INFO - Started process (PID=83987) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:05:58.325-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:05:58.327-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:05:58.327-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:05:58.335-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:05:58.334-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:05:58.336-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:05:58.378-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.066 seconds
[2025-02-23T03:06:58.164-0500] {processor.py:186} INFO - Started process (PID=84198) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:06:58.175-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:06:58.179-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:06:58.178-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:06:58.191-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:06:58.188-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:06:58.192-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:06:58.221-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.069 seconds
[2025-02-23T03:07:57.176-0500] {processor.py:186} INFO - Started process (PID=84380) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:07:57.180-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:07:57.186-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:07:57.185-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:07:57.204-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:07:57.200-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:07:57.205-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:07:57.328-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.163 seconds
[2025-02-23T03:09:02.886-0500] {processor.py:186} INFO - Started process (PID=84596) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:09:02.893-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:09:02.897-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:09:02.897-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:09:02.934-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:09:02.921-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:09:02.935-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:09:02.974-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.099 seconds
[2025-02-23T03:10:11.840-0500] {processor.py:186} INFO - Started process (PID=84822) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:10:11.842-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:10:11.845-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:10:11.845-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:10:11.853-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:10:11.851-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:10:11.853-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:10:11.887-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.056 seconds
[2025-02-23T03:11:11.218-0500] {processor.py:186} INFO - Started process (PID=85011) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:11:11.224-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:11:11.229-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:11:11.228-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:11:11.238-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:11:11.236-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:11:11.238-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:11:11.284-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.076 seconds
[2025-02-23T03:12:18.078-0500] {processor.py:186} INFO - Started process (PID=85241) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:12:18.081-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:12:18.084-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:12:18.084-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:12:18.097-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:12:18.091-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:12:18.097-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:12:18.134-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.071 seconds
[2025-02-23T03:13:18.239-0500] {processor.py:186} INFO - Started process (PID=85427) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:13:18.247-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:13:18.250-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:13:18.249-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:13:18.257-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:13:18.255-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:13:18.258-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:13:18.289-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.058 seconds
[2025-02-23T03:14:27.780-0500] {processor.py:186} INFO - Started process (PID=85692) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:14:27.782-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:14:27.785-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:14:27.785-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:14:27.793-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:14:27.792-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:14:27.794-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:14:27.824-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.056 seconds
[2025-02-23T03:15:36.797-0500] {processor.py:186} INFO - Started process (PID=85902) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:15:36.799-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:15:36.802-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:15:36.801-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:15:36.810-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:15:36.808-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:15:36.810-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:15:36.839-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.053 seconds
[2025-02-23T03:16:35.491-0500] {processor.py:186} INFO - Started process (PID=86124) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:16:35.493-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:16:35.496-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:16:35.495-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:16:35.503-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:16:35.502-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:16:35.504-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:16:35.536-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.054 seconds
[2025-02-23T03:17:36.226-0500] {processor.py:186} INFO - Started process (PID=86318) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:17:36.235-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:17:36.237-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:17:36.237-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:17:36.247-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:17:36.244-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:17:36.248-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:17:36.279-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.077 seconds
[2025-02-23T03:18:39.785-0500] {processor.py:186} INFO - Started process (PID=86629) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:18:39.787-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:18:39.790-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:18:39.790-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:18:39.798-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:18:39.796-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:18:39.798-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:18:39.830-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.054 seconds
[2025-02-23T03:19:42.155-0500] {processor.py:186} INFO - Started process (PID=86835) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:19:42.157-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:19:42.161-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:19:42.160-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:19:42.171-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:19:42.169-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:19:42.172-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:19:42.214-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.072 seconds
[2025-02-23T03:20:44.585-0500] {processor.py:186} INFO - Started process (PID=87035) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:20:44.587-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:20:44.590-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:20:44.589-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:20:44.598-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:20:44.596-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:20:44.599-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:20:44.630-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.053 seconds
[2025-02-23T03:21:44.115-0500] {processor.py:186} INFO - Started process (PID=87256) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:21:44.117-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:21:44.128-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:21:44.121-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:21:44.148-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:21:44.143-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:21:44.149-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:21:44.253-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.153 seconds
[2025-02-23T03:22:45.587-0500] {processor.py:186} INFO - Started process (PID=87468) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:22:45.593-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:22:45.596-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:22:45.596-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:22:45.604-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:22:45.602-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:22:45.605-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:22:45.637-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.059 seconds
[2025-02-23T03:23:49.371-0500] {processor.py:186} INFO - Started process (PID=87661) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:23:49.373-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:23:49.377-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:23:49.376-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:23:49.391-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:23:49.387-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:23:49.392-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:23:49.422-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.059 seconds
[2025-02-23T03:24:56.856-0500] {processor.py:186} INFO - Started process (PID=87879) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:24:56.858-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:24:56.861-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:24:56.860-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:24:56.868-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:24:56.867-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:24:56.869-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:24:56.905-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.058 seconds
[2025-02-23T03:25:57.783-0500] {processor.py:186} INFO - Started process (PID=88075) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:25:57.786-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:25:57.789-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:25:57.789-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:25:57.799-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:25:57.797-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:25:57.800-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:25:57.833-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.059 seconds
[2025-02-23T03:26:59.295-0500] {processor.py:186} INFO - Started process (PID=88304) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:26:59.305-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:26:59.309-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:26:59.309-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:26:59.325-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:26:59.322-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:26:59.326-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:26:59.384-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.099 seconds
[2025-02-23T03:27:55.764-0500] {processor.py:186} INFO - Started process (PID=88490) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:27:55.766-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:27:55.780-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:27:55.779-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:27:55.799-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:27:55.796-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:27:55.800-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:27:55.857-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.113 seconds
[2025-02-23T03:29:02.042-0500] {processor.py:186} INFO - Started process (PID=88703) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:29:02.049-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:29:02.052-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:29:02.052-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:29:02.060-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:29:02.058-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:29:02.060-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:29:02.092-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.059 seconds
[2025-02-23T03:30:04.783-0500] {processor.py:186} INFO - Started process (PID=88919) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:30:04.803-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:30:04.808-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:30:04.807-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:30:04.845-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:30:04.828-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:30:04.846-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:30:04.985-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.237 seconds
[2025-02-23T03:31:15.221-0500] {processor.py:186} INFO - Started process (PID=89199) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:31:15.223-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:31:15.225-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:31:15.225-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:31:15.233-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:31:15.232-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:31:15.234-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:31:15.266-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.055 seconds
[2025-02-23T03:32:22.514-0500] {processor.py:186} INFO - Started process (PID=89440) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:32:22.521-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:32:22.524-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:32:22.523-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:32:22.532-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:32:22.530-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:32:22.532-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:32:22.565-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.059 seconds
[2025-02-23T03:33:25.235-0500] {processor.py:186} INFO - Started process (PID=89653) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:33:25.242-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:33:25.245-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:33:25.245-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:33:25.256-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:33:25.253-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:33:25.256-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:33:25.290-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.068 seconds
[2025-02-23T03:34:32.785-0500] {processor.py:186} INFO - Started process (PID=89859) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:34:32.787-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:34:32.790-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:34:32.790-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:34:32.799-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:34:32.797-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:34:32.800-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:34:32.829-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.053 seconds
[2025-02-23T03:35:40.923-0500] {processor.py:186} INFO - Started process (PID=90100) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:35:40.925-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:35:40.928-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:35:40.928-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:35:40.936-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:35:40.934-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:35:40.937-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:35:40.974-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.059 seconds
[2025-02-23T03:36:46.170-0500] {processor.py:186} INFO - Started process (PID=90326) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:36:46.202-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:36:46.207-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:36:46.206-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:36:46.253-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:36:46.236-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:36:46.254-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:36:46.353-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.218 seconds
[2025-02-23T03:38:04.193-0500] {processor.py:186} INFO - Started process (PID=90561) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:38:04.195-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:38:04.199-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:38:04.198-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:38:04.208-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:38:04.207-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:38:04.209-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:38:04.243-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.059 seconds
[2025-02-23T03:39:06.266-0500] {processor.py:186} INFO - Started process (PID=90753) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:39:06.274-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:39:06.277-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:39:06.276-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:39:06.285-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:39:06.283-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:39:06.285-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:39:06.317-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.059 seconds
[2025-02-23T03:40:14.820-0500] {processor.py:186} INFO - Started process (PID=90987) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:40:14.822-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:40:14.826-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:40:14.825-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:40:14.837-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:40:14.835-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:40:14.838-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:40:14.876-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.070 seconds
[2025-02-23T03:41:20.314-0500] {processor.py:186} INFO - Started process (PID=91211) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:41:20.315-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py for tasks to queue
[2025-02-23T03:41:20.318-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:41:20.318-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:41:20.326-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:41:20.324-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 47, in <module>
    example_dag = example_display_name()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py", line 41, in example_display_name
    def sample_task_2():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:41:20.326-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py
[2025-02-23T03:41:20.358-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_display_name.py took 0.054 seconds
