[2025-02-22T23:43:21.241-0500] {processor.py:186} INFO - Started process (PID=26544) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:43:21.243-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:43:21.248-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:21.247-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:43:21.262-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:21.260-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:43:21.262-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:43:21.304-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.083 seconds
[2025-02-22T23:44:30.057-0500] {processor.py:186} INFO - Started process (PID=27047) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:44:30.060-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:44:30.064-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:30.063-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:44:30.087-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:30.086-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:44:30.088-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:44:30.120-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.075 seconds
[2025-02-22T23:49:05.312-0500] {processor.py:186} INFO - Started process (PID=27674) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:49:05.314-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:49:05.317-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:05.316-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:49:05.345-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:05.341-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:49:05.345-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:49:05.382-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.083 seconds
[2025-02-22T23:50:08.821-0500] {processor.py:186} INFO - Started process (PID=28142) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:50:08.823-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:50:08.825-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:08.825-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:50:08.843-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:08.842-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:50:08.843-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:50:08.873-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.060 seconds
[2025-02-22T23:51:05.264-0500] {processor.py:186} INFO - Started process (PID=28507) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:51:05.266-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:51:05.269-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:05.268-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:51:05.286-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:05.286-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:51:05.287-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:51:05.318-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.064 seconds
[2025-02-22T23:52:03.738-0500] {processor.py:186} INFO - Started process (PID=28953) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:52:03.740-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:52:03.744-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:03.743-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:52:03.758-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:03.757-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:52:03.759-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:52:03.789-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.059 seconds
[2025-02-22T23:53:05.529-0500] {processor.py:186} INFO - Started process (PID=29381) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:53:05.531-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:53:05.534-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:53:05.533-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:53:05.553-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:53:05.552-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:53:05.553-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:53:05.583-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.062 seconds
[2025-02-22T23:53:38.325-0500] {processor.py:186} INFO - Started process (PID=29610) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:53:38.327-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:53:38.336-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:53:38.335-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:53:38.355-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:53:38.353-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:53:38.356-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:53:38.391-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.076 seconds
[2025-02-22T23:54:45.036-0500] {processor.py:186} INFO - Started process (PID=30075) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:54:45.039-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:54:45.043-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:45.042-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:54:45.066-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:45.065-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:54:45.067-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:54:45.114-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.091 seconds
[2025-02-22T23:57:55.219-0500] {processor.py:186} INFO - Started process (PID=30570) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:57:55.224-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:57:55.229-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:57:55.228-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:57:55.250-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:57:55.248-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:57:55.251-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:57:55.286-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.081 seconds
[2025-02-22T23:58:41.531-0500] {processor.py:186} INFO - Started process (PID=30912) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:58:41.533-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:58:41.536-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:41.536-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:58:41.557-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:41.555-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:58:41.557-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:58:41.586-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.066 seconds
[2025-02-22T23:59:52.982-0500] {processor.py:186} INFO - Started process (PID=31356) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:59:53.167-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:59:53.172-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:53.171-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:59:53.303-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:53.301-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:59:53.304-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:59:53.442-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.493 seconds
[2025-02-23T00:01:10.341-0500] {processor.py:186} INFO - Started process (PID=31884) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:01:10.344-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:01:10.346-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:10.346-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:01:10.367-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:10.366-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:01:10.368-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:01:10.400-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.070 seconds
[2025-02-23T00:11:05.091-0500] {processor.py:186} INFO - Started process (PID=34404) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:11:05.093-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:11:05.100-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:05.099-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:11:05.110-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:05.109-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:11:05.111-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:11:05.140-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.058 seconds
[2025-02-23T00:12:05.762-0500] {processor.py:186} INFO - Started process (PID=34498) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:12:05.769-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:12:05.771-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:05.771-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:12:05.782-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:05.781-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:12:05.783-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:12:05.814-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.061 seconds
[2025-02-23T00:13:21.056-0500] {processor.py:186} INFO - Started process (PID=34607) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:13:21.057-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:13:21.060-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:21.060-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:13:21.070-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:21.070-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:13:21.071-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:13:21.102-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.054 seconds
[2025-02-23T00:14:17.421-0500] {processor.py:186} INFO - Started process (PID=34682) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:14:17.423-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:14:17.426-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:17.426-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:14:17.437-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:17.436-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:14:17.437-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:14:17.470-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.058 seconds
[2025-02-23T00:15:27.746-0500] {processor.py:186} INFO - Started process (PID=34776) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:15:27.753-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:15:27.760-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:27.759-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:15:27.768-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:27.767-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:15:27.769-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:15:27.800-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.061 seconds
[2025-02-23T00:16:27.646-0500] {processor.py:186} INFO - Started process (PID=34878) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:16:27.653-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:16:27.662-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:27.661-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:16:27.691-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:27.689-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:16:27.692-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:16:27.828-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.230 seconds
[2025-02-23T00:17:31.750-0500] {processor.py:186} INFO - Started process (PID=34953) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:17:31.751-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:17:31.754-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:31.754-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:17:31.763-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:31.762-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:17:31.764-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:17:31.793-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.052 seconds
[2025-02-23T00:18:32.167-0500] {processor.py:186} INFO - Started process (PID=35023) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:18:32.168-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:18:32.171-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:32.171-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:18:32.181-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:32.180-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:18:32.181-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:18:32.211-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.053 seconds
[2025-02-23T00:21:47.453-0500] {processor.py:186} INFO - Started process (PID=35162) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:21:47.460-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:21:47.467-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:21:47.466-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:21:47.475-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:21:47.475-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:21:47.476-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:21:47.511-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.066 seconds
[2025-02-23T00:22:48.066-0500] {processor.py:186} INFO - Started process (PID=35230) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:22:48.068-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:22:48.070-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:48.070-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:22:48.080-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:48.079-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:22:48.080-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:22:48.114-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.056 seconds
[2025-02-23T00:23:50.270-0500] {processor.py:186} INFO - Started process (PID=35295) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:23:50.276-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:23:50.280-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:50.279-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:23:50.318-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:50.314-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:23:50.319-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:23:50.403-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.147 seconds
[2025-02-23T00:24:52.614-0500] {processor.py:186} INFO - Started process (PID=35373) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:24:52.620-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:24:52.623-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:52.623-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:24:52.633-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:52.632-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:24:52.634-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:24:52.665-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.059 seconds
[2025-02-23T00:25:52.087-0500] {processor.py:186} INFO - Started process (PID=35440) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:25:52.088-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:25:52.091-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:52.091-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:25:52.101-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:52.100-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:25:52.101-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:25:52.134-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.056 seconds
[2025-02-23T02:31:32.789-0500] {processor.py:186} INFO - Started process (PID=75960) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:31:32.796-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:31:32.800-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:32.800-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:31:32.811-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:32.810-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:31:32.811-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:31:32.842-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.064 seconds
[2025-02-23T02:32:32.866-0500] {processor.py:186} INFO - Started process (PID=76385) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:32:32.869-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:32:32.873-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:32.872-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:32:32.888-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:32.887-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:32:32.889-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:32:32.919-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.066 seconds
[2025-02-23T02:33:50.072-0500] {processor.py:186} INFO - Started process (PID=76782) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:33:50.074-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:33:50.077-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:33:50.077-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:33:50.087-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:33:50.086-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:33:50.088-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:33:50.120-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.056 seconds
[2025-02-23T02:35:13.661-0500] {processor.py:186} INFO - Started process (PID=77108) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:35:13.665-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:35:13.671-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:35:13.670-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:35:13.697-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:35:13.695-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:35:13.698-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:35:13.808-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.169 seconds
[2025-02-23T02:43:40.557-0500] {processor.py:186} INFO - Started process (PID=79136) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:43:40.564-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:43:40.567-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:40.566-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:43:40.576-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:40.575-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:43:40.577-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:43:40.608-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.059 seconds
[2025-02-23T02:44:42.484-0500] {processor.py:186} INFO - Started process (PID=79339) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:44:42.486-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:44:42.490-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:42.489-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:44:42.501-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:42.500-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:44:42.501-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:44:42.543-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.070 seconds
