[2025-02-22T23:44:01.857-0500] {processor.py:186} INFO - Started process (PID=26845) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:44:01.859-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:44:01.863-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:01.862-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:44:01.868-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:01.867-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:44:01.868-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:01.868-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:44:01.868-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:44:01.880-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-02-22T23:48:40.006-0500] {processor.py:186} INFO - Started process (PID=27465) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:48:40.008-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:48:40.012-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:48:40.011-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:48:40.025-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:48:40.024-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:48:40.025-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:48:40.025-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:48:40.026-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:48:40.056-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-22T23:49:47.320-0500] {processor.py:186} INFO - Started process (PID=27982) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:49:47.322-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:49:47.325-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:47.324-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:49:47.330-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:47.329-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:49:47.330-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:47.330-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:49:47.331-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:49:47.343-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-22T23:50:45.164-0500] {processor.py:186} INFO - Started process (PID=28374) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:50:45.166-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:50:45.168-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:45.168-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:50:45.173-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:45.172-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:50:45.173-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:45.173-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:50:45.174-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:50:45.186-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-02-22T23:51:43.249-0500] {processor.py:186} INFO - Started process (PID=28764) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:51:43.251-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:51:43.254-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:43.253-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:51:43.260-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:43.260-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:51:43.261-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:43.261-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:51:43.261-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:51:43.274-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-22T23:52:44.326-0500] {processor.py:186} INFO - Started process (PID=29221) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:52:44.329-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:52:44.334-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:44.334-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:52:44.341-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:44.340-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:52:44.342-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:44.341-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:52:44.342-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:52:44.355-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2025-02-22T23:54:17.379-0500] {processor.py:186} INFO - Started process (PID=29874) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:54:17.381-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:54:17.385-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:17.384-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:54:17.392-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:17.392-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:54:17.393-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:17.393-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:54:17.393-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:54:17.407-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2025-02-22T23:57:28.056-0500] {processor.py:186} INFO - Started process (PID=30439) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:57:28.062-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:57:28.067-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:57:28.066-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:57:28.077-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:57:28.076-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:57:28.077-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:57:28.077-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:57:28.078-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:57:28.114-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2025-02-22T23:58:48.018-0500] {processor.py:186} INFO - Started process (PID=30935) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:58:48.020-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:58:48.025-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:48.023-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:58:48.035-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:48.034-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:58:48.035-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:48.035-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:58:48.035-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:58:48.054-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-02-23T00:00:01.682-0500] {processor.py:186} INFO - Started process (PID=31434) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:00:01.684-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:00:01.691-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:01.690-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:00:01.704-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:01.703-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:00:01.705-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:01.705-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:00:01.706-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:00:01.735-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T00:01:16.358-0500] {processor.py:186} INFO - Started process (PID=31908) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:01:16.360-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:01:16.363-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:16.362-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:01:16.368-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:16.367-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:01:16.368-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:16.368-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:01:16.368-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:01:16.381-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-23T00:11:40.657-0500] {processor.py:186} INFO - Started process (PID=34462) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:11:40.661-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:11:40.666-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:40.665-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:11:40.675-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:40.674-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:11:40.675-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:40.675-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:11:40.676-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:11:40.690-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.075 seconds
[2025-02-23T00:12:55.149-0500] {processor.py:186} INFO - Started process (PID=34574) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:12:55.151-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:12:55.156-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:55.155-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:12:55.160-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:55.160-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:12:55.160-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:55.160-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:12:55.161-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:12:55.175-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-23T00:13:53.855-0500] {processor.py:186} INFO - Started process (PID=34643) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:13:53.857-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:13:53.865-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:53.864-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:13:53.876-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:53.874-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:13:53.878-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:53.878-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:13:53.879-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:13:53.909-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-23T00:14:51.649-0500] {processor.py:186} INFO - Started process (PID=34718) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:14:51.654-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:14:51.660-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:51.659-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:14:51.668-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:51.667-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:14:51.670-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:51.668-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:14:51.670-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:14:51.691-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2025-02-23T00:16:01.667-0500] {processor.py:186} INFO - Started process (PID=34847) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:16:01.669-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:16:01.673-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:01.672-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:16:01.677-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:01.677-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:16:01.677-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:01.677-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:16:01.678-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:16:01.692-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2025-02-23T00:17:07.144-0500] {processor.py:186} INFO - Started process (PID=34922) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:17:07.151-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:17:07.154-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:07.154-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:17:07.159-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:07.158-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:17:07.159-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:07.159-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:17:07.159-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:17:07.172-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-02-23T00:18:06.175-0500] {processor.py:186} INFO - Started process (PID=34998) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:18:06.182-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:18:06.185-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:06.184-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:18:06.189-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:06.189-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:18:06.190-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:06.190-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:18:06.190-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:18:06.203-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-02-23T00:22:22.121-0500] {processor.py:186} INFO - Started process (PID=35205) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:22:22.123-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:22:22.126-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:22.125-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:22:22.131-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:22.130-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:22:22.131-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:22.131-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:22:22.132-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:22:22.147-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2025-02-23T00:23:25.643-0500] {processor.py:186} INFO - Started process (PID=35272) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:23:25.650-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:23:25.653-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:25.652-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:23:25.657-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:25.657-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:23:25.658-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:25.657-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:23:25.658-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:23:25.670-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-23T00:24:28.338-0500] {processor.py:186} INFO - Started process (PID=35350) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:24:28.339-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:24:28.343-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:28.342-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:24:28.348-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:28.347-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:24:28.348-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:28.348-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:24:28.349-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:24:28.363-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-23T00:25:27.872-0500] {processor.py:186} INFO - Started process (PID=35417) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:25:27.874-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:25:27.877-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:27.876-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:25:27.883-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:27.882-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:25:27.883-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:27.883-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:25:27.883-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:25:27.897-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-23T00:26:27.248-0500] {processor.py:186} INFO - Started process (PID=35492) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:26:27.250-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:26:27.253-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:26:27.252-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:26:27.257-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:26:27.257-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:26:27.258-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:26:27.258-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:26:27.258-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:26:27.271-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-02-23T02:31:54.886-0500] {processor.py:186} INFO - Started process (PID=76101) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:31:54.888-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:31:54.891-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:54.891-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:31:54.896-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:54.895-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:31:54.896-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:54.896-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:31:54.897-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:31:54.911-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-02-23T02:32:57.334-0500] {processor.py:186} INFO - Started process (PID=76472) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:32:57.339-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:32:57.343-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:57.342-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:32:57.347-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:57.347-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:32:57.348-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:57.347-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:32:57.348-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:32:57.364-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-02-23T02:34:11.511-0500] {processor.py:186} INFO - Started process (PID=76892) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:34:11.513-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:34:11.519-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:34:11.517-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:34:11.525-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:34:11.524-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:34:11.526-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:34:11.526-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:34:11.527-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:34:11.544-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-02-23T02:43:22.567-0500] {processor.py:186} INFO - Started process (PID=79082) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:43:22.569-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:43:22.572-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:22.571-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:43:22.577-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:22.576-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:43:22.578-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:22.577-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:43:22.578-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:43:22.593-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-23T02:44:21.821-0500] {processor.py:186} INFO - Started process (PID=79278) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:44:21.826-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:44:21.831-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:21.831-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:44:21.838-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:21.837-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:44:21.838-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:21.838-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:44:21.839-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:44:21.852-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
