[2025-02-22T23:43:16.302-0500] {processor.py:186} INFO - Started process (PID=26519) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:43:16.303-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-22T23:43:16.312-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:16.311-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:43:16.319-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:16.317-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:43:16.319-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:43:16.379-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.085 seconds
[2025-02-22T23:44:24.914-0500] {processor.py:186} INFO - Started process (PID=27024) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:44:24.916-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-22T23:44:24.919-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:24.918-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:44:24.929-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:24.924-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:44:24.930-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:44:24.961-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.055 seconds
[2025-02-22T23:49:00.335-0500] {processor.py:186} INFO - Started process (PID=27646) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:49:00.337-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-22T23:49:00.341-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:00.340-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:49:00.352-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:00.347-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:49:00.352-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:49:00.390-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.068 seconds
[2025-02-22T23:50:03.441-0500] {processor.py:186} INFO - Started process (PID=28101) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:50:03.444-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-22T23:50:03.448-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:03.447-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:50:03.454-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:03.453-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:50:03.455-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:50:03.490-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.059 seconds
[2025-02-22T23:50:59.974-0500] {processor.py:186} INFO - Started process (PID=28496) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:50:59.976-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-22T23:50:59.981-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:59.981-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:50:59.987-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:59.985-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:50:59.988-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:51:00.037-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.077 seconds
[2025-02-22T23:51:57.711-0500] {processor.py:186} INFO - Started process (PID=28922) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:51:57.714-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-22T23:51:57.718-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:57.717-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:51:57.730-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:57.724-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:51:57.731-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:51:57.765-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.064 seconds
[2025-02-22T23:52:59.700-0500] {processor.py:186} INFO - Started process (PID=29351) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:52:59.702-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-22T23:52:59.705-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:59.705-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:52:59.710-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:59.709-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:52:59.711-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:52:59.743-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.051 seconds
[2025-02-22T23:53:32.922-0500] {processor.py:186} INFO - Started process (PID=29573) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:53:32.924-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-22T23:53:32.929-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:53:32.928-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:53:32.944-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:53:32.942-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:53:32.948-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:53:33.162-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.265 seconds
[2025-02-22T23:54:38.386-0500] {processor.py:186} INFO - Started process (PID=30031) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:54:38.393-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-22T23:54:38.398-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:38.397-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:54:38.445-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:38.416-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:54:38.447-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:54:38.519-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.149 seconds
[2025-02-22T23:57:49.694-0500] {processor.py:186} INFO - Started process (PID=30529) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:57:49.696-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-22T23:57:49.699-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:57:49.698-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:57:49.704-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:57:49.703-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:57:49.704-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:57:49.733-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.047 seconds
[2025-02-22T23:58:36.349-0500] {processor.py:186} INFO - Started process (PID=30869) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:58:36.353-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-22T23:58:36.358-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:36.357-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:58:36.367-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:36.363-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:58:36.367-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:58:36.399-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.059 seconds
[2025-02-22T23:59:43.414-0500] {processor.py:186} INFO - Started process (PID=31314) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:59:43.446-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-22T23:59:43.450-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:43.450-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:59:43.486-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:43.484-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:59:43.487-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-22T23:59:43.639-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.259 seconds
[2025-02-23T00:00:24.992-0500] {processor.py:186} INFO - Started process (PID=31583) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:00:25.035-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T00:00:25.050-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:25.041-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:00:25.084-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:25.069-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:00:25.087-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:00:25.149-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.218 seconds
[2025-02-23T00:01:04.870-0500] {processor.py:186} INFO - Started process (PID=31861) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:01:04.876-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T00:01:04.888-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:04.887-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:01:04.913-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:04.903-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:01:04.917-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:01:04.992-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.154 seconds
[2025-02-23T00:02:03.770-0500] {processor.py:186} INFO - Started process (PID=32303) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:02:03.779-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T00:02:03.792-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:02:03.788-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:02:03.820-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:02:03.807-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:02:03.821-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:02:03.870-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.112 seconds
[2025-02-23T00:10:59.925-0500] {processor.py:186} INFO - Started process (PID=34389) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:10:59.928-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T00:10:59.932-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:10:59.931-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:10:59.936-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:10:59.935-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:10:59.936-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:10:59.971-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.053 seconds
[2025-02-23T00:12:00.762-0500] {processor.py:186} INFO - Started process (PID=34487) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:12:00.769-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T00:12:00.772-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:00.772-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:12:00.779-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:00.778-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:12:00.781-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:12:00.818-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.065 seconds
[2025-02-23T00:13:15.881-0500] {processor.py:186} INFO - Started process (PID=34602) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:13:15.888-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T00:13:15.891-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:15.891-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:13:15.896-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:15.895-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:13:15.897-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:13:15.929-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.060 seconds
[2025-02-23T00:14:12.193-0500] {processor.py:186} INFO - Started process (PID=34675) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:14:12.195-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T00:14:12.199-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:12.198-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:14:12.204-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:12.203-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:14:12.205-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:14:12.265-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.080 seconds
[2025-02-23T00:15:23.528-0500] {processor.py:186} INFO - Started process (PID=34758) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:15:23.535-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T00:15:23.539-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:23.539-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:15:23.543-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:23.542-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:15:23.544-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:15:23.580-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.062 seconds
[2025-02-23T00:16:21.202-0500] {processor.py:186} INFO - Started process (PID=34873) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:16:21.204-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T00:16:21.208-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:21.207-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:16:21.213-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:21.212-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:16:21.214-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:16:21.238-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.045 seconds
[2025-02-23T00:17:26.471-0500] {processor.py:186} INFO - Started process (PID=34944) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:17:26.474-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T00:17:26.477-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:26.476-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:17:26.482-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:26.481-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:17:26.483-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:17:26.517-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.054 seconds
[2025-02-23T00:18:26.996-0500] {processor.py:186} INFO - Started process (PID=35018) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:18:27.000-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T00:18:27.003-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:27.002-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:18:27.008-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:27.007-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:18:27.008-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:18:27.032-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.045 seconds
[2025-02-23T00:21:43.244-0500] {processor.py:186} INFO - Started process (PID=35157) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:21:43.251-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T00:21:43.255-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:21:43.254-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:21:43.259-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:21:43.258-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:21:43.259-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:21:43.301-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.065 seconds
[2025-02-23T00:22:42.899-0500] {processor.py:186} INFO - Started process (PID=35225) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:22:42.902-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T00:22:42.909-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:42.908-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:22:42.924-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:42.918-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:22:42.927-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:22:42.973-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.090 seconds
[2025-02-23T00:23:43.954-0500] {processor.py:186} INFO - Started process (PID=35290) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:23:43.956-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T00:23:43.958-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:43.958-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:23:43.963-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:43.962-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:23:43.963-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:23:43.989-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.044 seconds
[2025-02-23T00:24:47.444-0500] {processor.py:186} INFO - Started process (PID=35368) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:24:47.451-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T00:24:47.454-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:47.454-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:24:47.459-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:47.458-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:24:47.460-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:24:47.490-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.054 seconds
[2025-02-23T00:25:46.875-0500] {processor.py:186} INFO - Started process (PID=35435) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:25:46.882-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T00:25:46.885-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:46.885-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:25:46.889-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:46.888-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:25:46.890-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T00:25:46.922-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.055 seconds
[2025-02-23T02:31:27.586-0500] {processor.py:186} INFO - Started process (PID=75916) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:31:27.589-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T02:31:27.596-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:27.595-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:31:27.606-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:27.605-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:31:27.606-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:31:27.631-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.059 seconds
[2025-02-23T02:32:27.674-0500] {processor.py:186} INFO - Started process (PID=76366) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:32:27.683-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T02:32:27.686-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:27.686-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:32:27.691-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:27.690-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:32:27.692-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:32:27.723-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.057 seconds
[2025-02-23T02:33:45.022-0500] {processor.py:186} INFO - Started process (PID=76763) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:33:45.024-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T02:33:45.027-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:33:45.026-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:33:45.032-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:33:45.031-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:33:45.033-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:33:45.065-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.052 seconds
[2025-02-23T02:34:28.798-0500] {processor.py:186} INFO - Started process (PID=76975) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:34:28.800-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T02:34:28.805-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:34:28.804-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:34:28.813-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:34:28.811-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:34:28.813-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:34:28.867-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.085 seconds
[2025-02-23T02:43:35.473-0500] {processor.py:186} INFO - Started process (PID=79119) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:43:35.475-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T02:43:35.478-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:35.477-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:43:35.482-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:35.481-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:43:35.483-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:43:35.518-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.053 seconds
[2025-02-23T02:44:36.885-0500] {processor.py:186} INFO - Started process (PID=79322) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:44:36.887-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py for tasks to queue
[2025-02-23T02:44:36.890-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:36.890-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:44:36.895-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:36.894-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py", line 34, in <module>
    def my_py_command(params, test_mode=None, task=None):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:44:36.895-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py
[2025-02-23T02:44:36.940-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_passing_params_via_test_command.py took 0.075 seconds
