[2025-02-22T23:43:21.241-0500] {processor.py:186} INFO - Started process (PID=26544) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:43:21.243-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:43:21.248-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:21.247-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:43:21.262-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:21.260-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:43:21.262-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:43:21.304-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.083 seconds
[2025-02-22T23:44:30.057-0500] {processor.py:186} INFO - Started process (PID=27047) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:44:30.060-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:44:30.064-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:30.063-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:44:30.087-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:30.086-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:44:30.088-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:44:30.120-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.075 seconds
[2025-02-22T23:49:05.312-0500] {processor.py:186} INFO - Started process (PID=27674) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:49:05.314-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:49:05.317-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:05.316-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:49:05.345-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:05.341-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:49:05.345-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:49:05.382-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.083 seconds
[2025-02-22T23:50:08.821-0500] {processor.py:186} INFO - Started process (PID=28142) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:50:08.823-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:50:08.825-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:08.825-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:50:08.843-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:08.842-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:50:08.843-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:50:08.873-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.060 seconds
[2025-02-22T23:51:05.264-0500] {processor.py:186} INFO - Started process (PID=28507) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:51:05.266-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:51:05.269-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:05.268-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:51:05.286-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:05.286-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:51:05.287-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:51:05.318-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.064 seconds
[2025-02-22T23:52:03.738-0500] {processor.py:186} INFO - Started process (PID=28953) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:52:03.740-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:52:03.744-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:03.743-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:52:03.758-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:03.757-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:52:03.759-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:52:03.789-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.059 seconds
[2025-02-22T23:53:05.529-0500] {processor.py:186} INFO - Started process (PID=29381) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:53:05.531-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:53:05.534-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:53:05.533-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:53:05.553-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:53:05.552-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:53:05.553-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:53:05.583-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.062 seconds
[2025-02-22T23:53:38.325-0500] {processor.py:186} INFO - Started process (PID=29610) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:53:38.327-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:53:38.336-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:53:38.335-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:53:38.355-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:53:38.353-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:53:38.356-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:53:38.391-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.076 seconds
[2025-02-22T23:54:45.036-0500] {processor.py:186} INFO - Started process (PID=30075) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:54:45.039-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:54:45.043-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:45.042-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:54:45.066-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:45.065-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:54:45.067-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:54:45.114-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.091 seconds
[2025-02-22T23:57:55.219-0500] {processor.py:186} INFO - Started process (PID=30570) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:57:55.224-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:57:55.229-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:57:55.228-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:57:55.250-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:57:55.248-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:57:55.251-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:57:55.286-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.081 seconds
[2025-02-22T23:58:41.531-0500] {processor.py:186} INFO - Started process (PID=30912) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:58:41.533-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:58:41.536-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:41.536-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:58:41.557-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:41.555-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:58:41.557-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:58:41.586-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.066 seconds
[2025-02-22T23:59:52.982-0500] {processor.py:186} INFO - Started process (PID=31356) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:59:53.167-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-22T23:59:53.172-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:53.171-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:59:53.303-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:53.301-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:59:53.304-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-22T23:59:53.442-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.493 seconds
[2025-02-23T00:01:10.341-0500] {processor.py:186} INFO - Started process (PID=31884) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:01:10.344-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:01:10.346-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:10.346-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:01:10.367-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:10.366-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:01:10.368-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:01:10.400-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.070 seconds
[2025-02-23T00:11:05.091-0500] {processor.py:186} INFO - Started process (PID=34404) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:11:05.093-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:11:05.100-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:05.099-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:11:05.110-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:05.109-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:11:05.111-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:11:05.140-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.058 seconds
[2025-02-23T00:12:05.762-0500] {processor.py:186} INFO - Started process (PID=34498) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:12:05.769-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:12:05.771-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:05.771-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:12:05.782-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:05.781-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:12:05.783-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:12:05.814-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.061 seconds
[2025-02-23T00:13:21.056-0500] {processor.py:186} INFO - Started process (PID=34607) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:13:21.057-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:13:21.060-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:21.060-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:13:21.070-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:21.070-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:13:21.071-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:13:21.102-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.054 seconds
[2025-02-23T00:14:17.421-0500] {processor.py:186} INFO - Started process (PID=34682) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:14:17.423-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:14:17.426-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:17.426-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:14:17.437-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:17.436-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:14:17.437-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:14:17.470-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.058 seconds
[2025-02-23T00:15:27.746-0500] {processor.py:186} INFO - Started process (PID=34776) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:15:27.753-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:15:27.760-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:27.759-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:15:27.768-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:27.767-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:15:27.769-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:15:27.800-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.061 seconds
[2025-02-23T00:16:27.646-0500] {processor.py:186} INFO - Started process (PID=34878) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:16:27.653-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:16:27.662-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:27.661-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:16:27.691-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:27.689-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:16:27.692-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:16:27.828-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.230 seconds
[2025-02-23T00:17:31.750-0500] {processor.py:186} INFO - Started process (PID=34953) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:17:31.751-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:17:31.754-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:31.754-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:17:31.763-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:31.762-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:17:31.764-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:17:31.793-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.052 seconds
[2025-02-23T00:18:32.167-0500] {processor.py:186} INFO - Started process (PID=35023) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:18:32.168-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:18:32.171-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:32.171-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:18:32.181-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:32.180-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:18:32.181-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:18:32.211-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.053 seconds
[2025-02-23T00:21:47.453-0500] {processor.py:186} INFO - Started process (PID=35162) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:21:47.460-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:21:47.467-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:21:47.466-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:21:47.475-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:21:47.475-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:21:47.476-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:21:47.511-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.066 seconds
[2025-02-23T00:22:48.066-0500] {processor.py:186} INFO - Started process (PID=35230) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:22:48.068-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:22:48.070-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:48.070-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:22:48.080-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:48.079-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:22:48.080-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:22:48.114-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.056 seconds
[2025-02-23T00:23:50.270-0500] {processor.py:186} INFO - Started process (PID=35295) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:23:50.276-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:23:50.280-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:50.279-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:23:50.318-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:50.314-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:23:50.319-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:23:50.403-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.147 seconds
[2025-02-23T00:24:52.614-0500] {processor.py:186} INFO - Started process (PID=35373) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:24:52.620-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:24:52.623-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:52.623-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:24:52.633-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:52.632-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:24:52.634-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:24:52.665-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.059 seconds
[2025-02-23T00:25:52.087-0500] {processor.py:186} INFO - Started process (PID=35440) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:25:52.088-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T00:25:52.091-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:52.091-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:25:52.101-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:52.100-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:25:52.101-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T00:25:52.134-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.056 seconds
[2025-02-23T02:31:32.789-0500] {processor.py:186} INFO - Started process (PID=75960) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:31:32.796-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:31:32.800-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:32.800-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:31:32.811-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:32.810-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:31:32.811-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:31:32.842-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.064 seconds
[2025-02-23T02:32:32.866-0500] {processor.py:186} INFO - Started process (PID=76385) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:32:32.869-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:32:32.873-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:32.872-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:32:32.888-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:32.887-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:32:32.889-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:32:32.919-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.066 seconds
[2025-02-23T02:33:50.072-0500] {processor.py:186} INFO - Started process (PID=76782) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:33:50.074-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:33:50.077-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:33:50.077-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:33:50.087-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:33:50.086-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:33:50.088-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:33:50.120-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.056 seconds
[2025-02-23T02:35:13.661-0500] {processor.py:186} INFO - Started process (PID=77108) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:35:13.665-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:35:13.671-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:35:13.670-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:35:13.697-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:35:13.695-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:35:13.698-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:35:13.808-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.169 seconds
[2025-02-23T02:43:40.557-0500] {processor.py:186} INFO - Started process (PID=79136) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:43:40.564-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:43:40.567-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:40.566-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:43:40.576-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:40.575-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:43:40.577-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:43:40.608-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.059 seconds
[2025-02-23T02:44:42.484-0500] {processor.py:186} INFO - Started process (PID=79339) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:44:42.486-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:44:42.490-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:42.489-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:44:42.501-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:42.500-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:44:42.501-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:44:42.543-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.070 seconds
[2025-02-23T02:45:45.069-0500] {processor.py:186} INFO - Started process (PID=79538) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:45:45.073-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:45:45.077-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:45:45.077-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:45:45.096-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:45:45.091-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:45:45.098-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:45:45.133-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.081 seconds
[2025-02-23T02:46:47.255-0500] {processor.py:186} INFO - Started process (PID=79761) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:46:47.257-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:46:47.260-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:46:47.260-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:46:47.272-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:46:47.271-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:46:47.273-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:46:47.308-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.070 seconds
[2025-02-23T02:47:56.612-0500] {processor.py:186} INFO - Started process (PID=79969) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:47:56.615-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:47:56.618-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:47:56.618-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:47:56.639-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:47:56.631-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:47:56.640-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:47:56.693-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.089 seconds
[2025-02-23T02:48:59.633-0500] {processor.py:186} INFO - Started process (PID=80167) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:48:59.637-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:48:59.640-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:48:59.640-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:48:59.651-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:48:59.650-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:48:59.652-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:48:59.688-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.065 seconds
[2025-02-23T02:50:19.438-0500] {processor.py:186} INFO - Started process (PID=80398) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:50:19.441-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:50:19.454-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:50:19.453-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:50:19.485-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:50:19.483-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:50:19.486-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:50:19.542-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.126 seconds
[2025-02-23T02:51:37.354-0500] {processor.py:186} INFO - Started process (PID=80649) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:51:37.355-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:51:37.358-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:51:37.358-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:51:37.368-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:51:37.367-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:51:37.369-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:51:37.408-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.063 seconds
[2025-02-23T02:52:45.634-0500] {processor.py:186} INFO - Started process (PID=80856) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:52:45.637-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:52:45.640-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:52:45.639-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:52:45.652-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:52:45.650-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:52:45.652-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:52:45.681-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.057 seconds
[2025-02-23T02:53:47.925-0500] {processor.py:186} INFO - Started process (PID=81042) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:53:47.932-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:53:47.937-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:53:47.936-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:53:47.948-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:53:47.947-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:53:47.949-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:53:47.983-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.069 seconds
[2025-02-23T02:54:53.042-0500] {processor.py:186} INFO - Started process (PID=81246) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:54:53.049-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:54:53.055-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:54:53.054-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:54:53.067-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:54:53.065-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:54:53.068-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:54:53.109-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.083 seconds
[2025-02-23T02:55:55.439-0500] {processor.py:186} INFO - Started process (PID=81433) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:55:55.446-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:55:55.449-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:55:55.448-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:55:55.459-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:55:55.457-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:55:55.459-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:55:55.491-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.063 seconds
[2025-02-23T02:56:54.823-0500] {processor.py:186} INFO - Started process (PID=81645) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:56:54.824-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:56:54.827-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:56:54.827-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:56:54.838-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:56:54.837-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:56:54.838-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:56:54.878-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.066 seconds
[2025-02-23T02:58:02.611-0500] {processor.py:186} INFO - Started process (PID=81882) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:58:02.618-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:58:02.622-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:58:02.622-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:58:02.637-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:58:02.636-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:58:02.637-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:58:02.668-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.067 seconds
[2025-02-23T02:59:02.956-0500] {processor.py:186} INFO - Started process (PID=82067) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:59:02.963-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T02:59:02.968-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:59:02.967-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:59:02.985-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:59:02.980-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:59:02.987-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T02:59:03.020-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.073 seconds
[2025-02-23T03:00:05.470-0500] {processor.py:186} INFO - Started process (PID=82260) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:00:05.472-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:00:05.475-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:00:05.474-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:00:05.485-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:00:05.484-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:00:05.485-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:00:05.524-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.062 seconds
[2025-02-23T03:01:13.093-0500] {processor.py:186} INFO - Started process (PID=82478) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:01:13.099-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:01:13.102-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:01:13.101-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:01:13.115-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:01:13.113-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:01:13.116-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:01:13.154-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.071 seconds
[2025-02-23T03:02:24.701-0500] {processor.py:186} INFO - Started process (PID=82722) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:02:24.707-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:02:24.710-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:02:24.709-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:02:24.733-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:02:24.732-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:02:24.734-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:02:24.765-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.090 seconds
[2025-02-23T03:03:16.714-0500] {processor.py:186} INFO - Started process (PID=83457) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:03:16.748-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:03:16.751-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:03:16.751-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:03:16.764-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:03:16.763-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:03:16.765-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:03:17.063-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.363 seconds
[2025-02-23T03:04:25.305-0500] {processor.py:186} INFO - Started process (PID=83701) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:04:25.307-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:04:25.310-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:04:25.310-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:04:25.328-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:04:25.327-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:04:25.329-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:04:25.361-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.065 seconds
[2025-02-23T03:05:29.276-0500] {processor.py:186} INFO - Started process (PID=83897) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:05:29.348-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:05:29.352-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:05:29.351-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:05:29.367-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:05:29.365-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:05:29.367-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:05:29.401-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.136 seconds
[2025-02-23T03:06:30.877-0500] {processor.py:186} INFO - Started process (PID=84120) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:06:30.884-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:06:30.887-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:06:30.886-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:06:30.896-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:06:30.896-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:06:30.897-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:06:30.929-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.061 seconds
[2025-02-23T03:07:30.224-0500] {processor.py:186} INFO - Started process (PID=84299) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:07:30.233-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:07:30.238-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:07:30.237-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:07:30.275-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:07:30.274-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:07:30.276-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:07:30.385-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.181 seconds
[2025-02-23T03:08:34.470-0500] {processor.py:186} INFO - Started process (PID=84495) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:08:34.471-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:08:34.474-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:08:34.474-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:08:34.486-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:08:34.484-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:08:34.486-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:08:34.522-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.063 seconds
[2025-02-23T03:09:36.877-0500] {processor.py:186} INFO - Started process (PID=84717) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:09:36.879-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:09:36.882-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:09:36.881-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:09:36.892-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:09:36.891-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:09:36.892-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:09:36.928-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.061 seconds
[2025-02-23T03:10:43.804-0500] {processor.py:186} INFO - Started process (PID=84920) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:10:43.806-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:10:43.810-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:10:43.809-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:10:43.820-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:10:43.819-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:10:43.821-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:10:43.852-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.058 seconds
[2025-02-23T03:11:46.336-0500] {processor.py:186} INFO - Started process (PID=85137) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:11:46.338-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:11:46.340-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:11:46.340-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:11:46.352-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:11:46.351-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:11:46.353-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:11:46.387-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.060 seconds
[2025-02-23T03:12:49.346-0500] {processor.py:186} INFO - Started process (PID=85332) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:12:49.353-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:12:49.357-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:12:49.356-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:12:49.371-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:12:49.370-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:12:49.371-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:12:49.406-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.073 seconds
[2025-02-23T03:13:59.696-0500] {processor.py:186} INFO - Started process (PID=85541) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:13:59.703-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:13:59.706-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:13:59.705-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:13:59.743-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:13:59.742-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:13:59.745-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:13:59.806-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.128 seconds
[2025-02-23T03:15:02.620-0500] {processor.py:186} INFO - Started process (PID=85803) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:15:02.631-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:15:02.634-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:15:02.633-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:15:02.644-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:15:02.643-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:15:02.645-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:15:02.677-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.067 seconds
[2025-02-23T03:16:09.263-0500] {processor.py:186} INFO - Started process (PID=86006) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:16:09.265-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:16:09.269-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:16:09.268-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:16:09.279-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:16:09.278-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:16:09.280-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:16:09.314-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.061 seconds
[2025-02-23T03:17:07.227-0500] {processor.py:186} INFO - Started process (PID=86229) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:17:07.234-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:17:07.238-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:17:07.237-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:17:07.251-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:17:07.249-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:17:07.252-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:17:07.283-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.065 seconds
[2025-02-23T03:18:11.278-0500] {processor.py:186} INFO - Started process (PID=86434) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:18:11.285-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:18:11.288-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:18:11.288-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:18:11.298-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:18:11.297-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:18:11.299-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:18:11.332-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.063 seconds
[2025-02-23T03:19:15.620-0500] {processor.py:186} INFO - Started process (PID=86752) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:19:15.622-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:19:15.625-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:19:15.624-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:19:15.638-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:19:15.637-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:19:15.639-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:19:15.674-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.065 seconds
[2025-02-23T03:20:18.134-0500] {processor.py:186} INFO - Started process (PID=86950) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:20:18.142-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:20:18.145-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:20:18.144-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:20:18.155-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:20:18.154-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:20:18.155-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:20:18.192-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.066 seconds
[2025-02-23T03:21:19.531-0500] {processor.py:186} INFO - Started process (PID=87171) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:21:19.533-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:21:19.536-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:21:19.536-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:21:19.555-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:21:19.546-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:21:19.555-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:21:19.589-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.067 seconds
[2025-02-23T03:22:18.328-0500] {processor.py:186} INFO - Started process (PID=87381) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:22:18.335-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:22:18.337-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:22:18.337-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:22:18.348-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:22:18.347-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:22:18.349-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:22:18.383-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.066 seconds
[2025-02-23T03:23:24.550-0500] {processor.py:186} INFO - Started process (PID=87588) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:23:24.557-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:23:24.560-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:23:24.560-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:23:24.570-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:23:24.569-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:23:24.570-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:23:24.601-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.063 seconds
[2025-02-23T03:24:25.388-0500] {processor.py:186} INFO - Started process (PID=87776) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:24:25.395-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:24:25.398-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:24:25.397-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:24:25.407-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:24:25.406-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:24:25.408-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:24:25.445-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.066 seconds
[2025-02-23T03:25:32.764-0500] {processor.py:186} INFO - Started process (PID=88001) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:25:32.773-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:25:32.776-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:25:32.776-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:25:32.786-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:25:32.785-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:25:32.786-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:25:32.818-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.063 seconds
[2025-02-23T03:26:32.931-0500] {processor.py:186} INFO - Started process (PID=88223) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:26:32.933-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:26:32.935-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:26:32.935-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:26:32.945-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:26:32.944-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:26:32.946-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:26:32.977-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.054 seconds
[2025-02-23T03:27:31.893-0500] {processor.py:186} INFO - Started process (PID=88417) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:27:31.894-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:27:31.897-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:27:31.897-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:27:31.907-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:27:31.906-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:27:31.908-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:27:31.942-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.063 seconds
[2025-02-23T03:28:32.044-0500] {processor.py:186} INFO - Started process (PID=88601) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:28:32.050-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:28:32.053-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:28:32.053-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:28:32.063-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:28:32.062-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:28:32.064-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:28:32.101-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.066 seconds
[2025-02-23T03:29:33.063-0500] {processor.py:186} INFO - Started process (PID=88801) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:29:33.066-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:29:33.071-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:29:33.070-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:29:33.088-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:29:33.086-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:29:33.088-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:29:33.141-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.116 seconds
[2025-02-23T03:30:44.615-0500] {processor.py:186} INFO - Started process (PID=89077) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:30:44.617-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:30:44.622-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:30:44.621-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:30:44.635-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:30:44.634-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:30:44.636-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:30:44.668-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.063 seconds
[2025-02-23T03:31:45.653-0500] {processor.py:186} INFO - Started process (PID=89327) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:31:45.655-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:31:45.664-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:31:45.663-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:31:45.691-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:31:45.688-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:31:45.693-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:31:45.745-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.108 seconds
[2025-02-23T03:32:53.888-0500] {processor.py:186} INFO - Started process (PID=89547) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:32:53.896-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:32:53.898-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:32:53.898-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:32:53.908-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:32:53.907-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:32:53.909-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:32:53.939-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.059 seconds
[2025-02-23T03:34:02.804-0500] {processor.py:186} INFO - Started process (PID=89764) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:34:02.811-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:34:02.814-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:34:02.813-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:34:02.825-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:34:02.824-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:34:02.826-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:34:02.863-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.068 seconds
[2025-02-23T03:35:09.875-0500] {processor.py:186} INFO - Started process (PID=89999) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:35:09.882-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:35:09.885-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:35:09.884-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:35:09.894-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:35:09.893-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:35:09.895-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:35:09.928-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.062 seconds
[2025-02-23T03:36:14.412-0500] {processor.py:186} INFO - Started process (PID=90210) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:36:14.414-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:36:14.417-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:36:14.416-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:36:14.428-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:36:14.426-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:36:14.429-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:36:14.466-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.065 seconds
[2025-02-23T03:37:30.366-0500] {processor.py:186} INFO - Started process (PID=90459) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:37:30.373-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:37:30.377-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:37:30.376-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:37:30.404-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:37:30.403-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:37:30.407-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:37:30.446-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.089 seconds
[2025-02-23T03:38:35.824-0500] {processor.py:186} INFO - Started process (PID=90658) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:38:35.849-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:38:35.853-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:38:35.852-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:38:35.875-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:38:35.874-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:38:35.875-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:38:35.903-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.103 seconds
[2025-02-23T03:39:40.614-0500] {processor.py:186} INFO - Started process (PID=90858) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:39:40.616-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:39:40.619-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:39:40.619-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:39:40.637-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:39:40.636-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:39:40.639-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:39:40.708-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.106 seconds
[2025-02-23T03:40:50.260-0500] {processor.py:186} INFO - Started process (PID=91086) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:40:50.262-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py for tasks to queue
[2025-02-23T03:40:50.265-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:40:50.264-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:40:50.274-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:40:50.273-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py", line 45, in <module>
    def dataset_with_extra_by_yield():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:40:50.274-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py
[2025-02-23T03:40:50.305-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_outlet_event_extra.py took 0.054 seconds
